Neos:
  ContentRepository:
    contentDimensions:
      'language':
        default: 'en'
        defaultPreset: 'en'
        label: 'Language'
        icon: 'icon-language'
        presets:
          'en':
            label: 'English'
            values: [ 'en' ]
            uriSegment: ''
          'de':
            label: 'German'
            values: [ 'de', 'en' ]
            uriSegment: 'de'
